# change to false to stop auto-update-check
auto-update-check: default
# color of [CANCEL]
cancelcolor: default
# set to true to broadcast "<player> canceled sleep."
# set to false not to broadcast that msg.
cancelbroadcast: default
# set to true before sending a log about an issue.
#logs trace data required to pinpoint where errors are.
debug: default
lang: default