# Change to false to stop auto-update-check.
auto-update-check: true

# If true this will disable all broadcast messages and allow anyone to sleep.
unrestrictedsleep: false

# Set the color of the [CANCEL] link text in broadcast messages.
cancelcolor: RED

# Set to true to broadcast "<player> canceled sleep."
# Set to false not to broadcast that message.
cancelbroadcast: true

# Set the time limit in seconds which a player must wait between attempting to sleep again.
# This prevents a user from spamming chat with sleep messages.
# Set to 0 to disable.
sleeplimit: 60

# Set to true before sending a log about an issue.
# Logs trace data required to pinpoint where errors are.
debug: false

# Set the language to use, check inside lang.yml for the available translations.
lang: en_US
