# Change to false to stop auto-update-check.
auto-update-check: true

# If true this will disable all broadcast messages and allow anyone to sleep.
unrestrictedsleep: false

# Set the color of the players name in the broadcast messages.
# NOTE: If you change the players display name color using other plugins then you should set this to "NONE".
namecolor: NONE

# Set the color of the [CANCEL] link text in broadcast messages. Format RED
# Colors: AQUA, BLACK, GOLD, GRAY, BLUE, GREEN, RED, YELLOW, WHITE
# DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_RED, DARK_PURPLE, LIGHT_PURPLE
# MAGIC, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
cancelcolor: RED
# Sleep message color, use either YELLOW
sleepmsgcolor: YELLOW
# Player name color, use either WHITE
playernamecolor: WHITE

# Set to true to broadcast "<player> canceled sleep."
# Set to false not to broadcast that message.
cancelbroadcast: true

# Set the time limit in seconds which a player must wait between attempting to sleep again.
# This prevents a user from spamming chat with sleep messages.
# Set to 0 to disable.
sleeplimit: 60

# Set to true before sending a log about an issue.
# Logs trace data required to pinpoint where errors are.
debug: false

# Set the language to use, check inside lang.yml for the available translations.
lang: en_US

# Set to true to use random sleep msgs.
randomsleepmsgs: true

# Set to the number of sleep msgs
numberofsleepmsgs: 4
# Set msgs for random sleep msgs here "sleepmsg#: <player> msg here"
# Don't forget the space between : and the start of the message.
sleepmsg1: <player> is sleeping
sleepmsg2: <player> went to bed. Sweet dreams
sleepmsg3: Shhh! <player> is trying to sleep!
sleepmsg4: <player> is asleep at the wheel